# Generated by Django 2.2.2 on 2019-07-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Char',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('char_class', models.CharField(choices=[('M', 'M'), ('T', 'T'), ('F', 'F')], default='M', max_length=1)),
                ('vit', models.IntegerField(default=0)),
                ('ten', models.IntegerField(default=0)),
                ('stren', models.IntegerField(default=0)),
                ('dex', models.IntegerField(default=0)),
                ('awa', models.IntegerField(default=0)),
                ('cha', models.IntegerField(default=0)),
                ('ms', models.IntegerField(default=0)),
                ('mag', models.IntegerField(default=0)),
                ('intel', models.IntegerField(default=0)),
                ('perks', models.TextField(max_length=10000)),
                ('flaws', models.TextField(max_length=5000)),
            ],
        ),
    ]
